#!/bin/dash

if [ ! -d ".shrug" ] #Check if .shrug exists
then
    echo "shrug-log: error: no .shrug directory containing shrug repository exists"
    exit 1
fi

cd .shrug 
if [ -f "version" ] #A commit must exist
then
    ver=`cat version`
    cd messages
    for i in `seq $ver -1 0`;
    do
        cat message$i 
    done
else
    echo "shrug-log: error: your repository does not have any commits yet"
    exit 1
fi

